/* IMPORTANT: the array in this file needs to be 1:1 with the one in
 duplicated_icons.js, except for the extension that has to be json */

const duplicatedIconsModels = [
  'battery_20.json',
  'battery_30.json',
  'battery_50.json',
  'battery_60.json',
  'battery_80.json',
  'battery_90.json',
  'battery_std.json',
  'battery_charging_30.json',
  'battery_charging_50.json',
  'battery_charging_60.json',
  'battery_charging_80.json',
  'battery_charging_90.json',
  'battery_charging_full.json',
  'clear.json',
  'dns.json',
  'expand_more.json',
  'expand_less.json',
  'navigate_before.json',
  'navigate_next.json',
  'chevron_left.json',
  'chevron_right.json',
  'settings_input_composite.json',
  'signal_cellular_0_bar.json',
  'signal_cellular_1_bar.json',
  'signal_cellular_2_bar.json',
  'signal_cellular_3_bar.json',
  'signal_cellular_4_bar.json',
  'signal_cellular_connected_no_internet_0_bar.json',
  'signal_cellular_connected_no_internet_1_bar.json',
  'signal_cellular_connected_no_internet_2_bar.json',
  'signal_cellular_connected_no_internet_3_bar.json',
  'signal_cellular_connected_no_internet_4_bar.json',
  'wb_cloudy.json',
  'signal_wifi_0_bar.json',
  'signal_wifi_1_bar.json',
  'signal_wifi_2_bar.json',
  'signal_wifi_3_bar.json',
  'signal_wifi_4_bar.json',
  'signal_wifi_1_bar_lock.json',
  'signal_wifi_2_bar_lock.json',
  'signal_wifi_3_bar_lock.json',
  'signal_wifi_4_bar_lock.json',
  'access_alarms.json',
  'alarm_add.json',
  'brightness_5.json',
  'brightness_6.json',
  'brightness_7.json',
  'local_hotel.json',
  'mail.json',
  'markunread.json',
  'perm_identity.json',
  'bluetooth_audio.json',
  'stay_primary_landscape.json',
  'stay_primary_portrait.json',
  'local_airport.json',
  'flight.json',
  'photo_camera.json',
]

module.exports = {
  duplicatedIconsModels
}
